baseurl: "https://liyanplus.github.io/geoindustry_2022.github.io/"
title: "International Workshop on Spatial Big Data and AI for Industrial Applications@ACM SIGSPATIAL 2022"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "GeoIndustry@ACM SIGSPATIAL 2022"
  Description: "International Workshop on Spatial Big Data and AI for Industrial Applications@ACM SIGSPATIAL 2022"
  Date: "November 1, 2022, Pacific Standard Time"
  # Price: "Only $100" # If your event is free, just comment this line
  Venue: "Seattle Marriott Waterfront"
  Address: "2100 Alaskan Way"
  City:  "Seattle"
  State: "WA"
  Images: ["/img/logo.png"]
  big_logo: "/images/acmsigspatial-full.png"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - intro
    - organizer
    # - speakers
    - schedule    
    - location
    - cfp
    - deadline
    #- contact

  # Titles which you can translate to other languages
  Titles:
    intro: "About"
    location: "Location"
    cfp: "Call For Papers"
    organizer: "Organization Committee"
    # speakers: "Invited Talk"
    schedule: "Schedule"
    deadline: "Important Dates"
    # sponsors: "Sponsors"
    # partners: "Partners"
    # contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now"
    link: "https://sigspatial2022.sigspatial.org/registration/"

  intro:
    text: "With the rapid revolution and increasing availability of geospatial data, not only academia but also industry aspire 
        for solutions to further leverage the big data and AI technologies to create new products, improve efficiencies and 
        provide novel solutions to existing problems. However, despite the widespread interest, there is a lack of communication 
        between the researchers in academia and industry, limiting advancements at the intersection. Academia often has 
        limited access to the rich and potentially useful big geospatial datasets and related real problems. In addition, 
        the solutions proposed by the academic researchers alone are usually developed for small scale with many assumptions, 
        leaving a less-attended gap between methods and their applicability at scale for industrial applications. On the other hand, 
        industry has the data and problems at scale. However, since existing research is often not on par, industry researchers may 
        lean towards using the traditional approaches that are developed without spatial consideration (e.g., ignoring spatial and 
        temporal dependencies), and project teams have limited time and efforts to dive deep on the development of novel techniques 
        that can be high-risk but high-potential. This opens up opportunities for synergistic collaboration between industrial 
        practitioners and academic researchers. The 1st ACM SIGSPATIAL International Workshop on Spatial Big Data and AI for Industrial 
        Applications (GeoIndustry 2022) is to offer a forum to exchange thoughts and ideas between industry and academia and reduce the 
        siloed efforts. At the same time, the collaborations, via invited and regular talks, can not only accelerate the research-to-impact 
        cycle, but also foster workforce development for future geospatial researchers. "

  cfp:
    text: ""
    url: "files/CFP22_GeoIndustry_SIGSPATIAL.pdf"
    keywords: [""]

  organizer:
    pc_chair: ["Emre Eftelioglu (Amazon)",
    "Heba Aly (Amazon)", 
    "Yiqun Xie (University of Maryland)",
    "Jia Yu (Washington State University, Apache Software Foundation)"]
    pc_member: ["Ravi Garg (Amazon)",
    "Xiaowei Jia (University of Pittsburgh)",
    "Zhe Jiang (University of Florida)",
    "Xun Tang (Meta)"]
    webmaster: ["Yan Li (Amazon)"]

  deadline:
    submission: "September 16, 2022 (anywhere on earth, extended)"
    notification: "September 28, 2022 (anywhere on earth)"
    camera: "October 10, 2022 (anywhere on earth)"
    workshopdate: "November 1, 2022"
    submissionsite: "https://easychair.org/my/conference?conf=geoindustry22"

  schedule:
    - time: "09:00 - 09:10"
      title: "Opening Remarks"
    - time: "09:10 - 10:10"
      authors: "Dr. John Krumm"
      title: "Keynote Talk" 
    - time: "10:10 - 10:30"
      title: "BinoML: Supervised Ranking for Automatic Building Labeling"
      authors: "Puyang Ma, Ravi Garg, Mohamed Moustafa"
      abstract: ""
    - time: "10:30 - 10:50"
      authors: "Coffee Break"
    - time: "10:50 - 11:10"
      title: "Toward a crowdsourcing solution to estimate border crossing times using market-available connected vehicle data"
      authors: "Ehsan Jalilifar, Xiao Li, Michael Martin, Xiao Huang"
    - time: "11:10 - 11:30"
      title: "A Study on Singaporeâ€™s Vegetation Cover and Land Use Change Using Remote Sensing"
      authors: "Yun Si Goh, Jing Wen Leong, Seanglidet Yean, Bu-Sung Lee, Kang Min Ngo, Peter Edwards"
    - time: "11:30 - 11:50"
      authors: "Break"
    - time: "11:50 - 12:50"
      authors: "Dr. Dieter Pfoser"
      title: "Keynote Talk" 
    - time: "12:50 - 13:00"
      title: "Closing Remarks"
